# FROM nvcr.io/nvidia/tensorflow:23.01-tf2-py3
FROM nvcr.io/nvidia/tensorflow:22.05-tf2-py3
WORKDIR /workspace
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN pip3 install sentencepiece
RUN pip3 install evaluate
RUN pip3 install rouge_score
RUN pip3 install torch

# CMD jupyter lab --ip=0.0.0.0 --allow-root
